### ISSUE TITLE
Camera Normalization on DTU dataset

### ISSUE THREAD

**Issue by o0Helloworld0o** [fdarmon/NeuralWarp#7]
Dear author,
    Thank you for your open source code. I notice that volsdf normalize the camera (within a sphere with R=3) on DTU dataset. However, NeuralWarp loads camera params from the original cameras.npz, which is not normalized. Since this project is built upon volsdf, I want to know why the author removed the camera normalization step. Moreover, I think the default value of --bbox_size in extract_mesh.py is not much reasonable. It should be set carefully for each scene because the camera is not normalized. If the value is too large, then a lot of empty space is wasted. If the value is too small, the extracted mesh is defective.
    I want to hear the author's viewpoint on this.
Thanks!

**Comment by fdarmon** [comment]
HI, sorry for the late reply. 

This project was not exactly built on VolSDF, I reimplemented VolSDF starting from IDR code. I did not try to normalize the camera but I do not expect the result to vary a lot since the results with my implemntation of VolSDF are close to the original ones. 

I agree`--bbox_size` is not very precise but I use a code from IDR that extracts the meshes in two steps. It first extracts the mesh using the full bbox_size, then it re-extracts another mesh but this time using a much smaller bounding box. This smaller bounding box comes from mesh obtained at the first step. 

I hope this helps
